# AUTO-GENERATED FILE.
# DO NOT EDIT.
# Generated by eskit.tools.generate_events.

"""Generated event definitions."""

from typing import Any

from eskit.events.bus import EventBus
from eskit.events.event import Event

AI_RUN_STARTED = 1001
AI_LLM_PROMPT = 1002
AI_LLM_RESPONSE = 1003
AI_TOOL_CALL = 1004
AI_TOOL_RESULT = 1005
AI_USER_INPUT = 1006
AI_FINAL_RESPONSE = 1007
AI_ERROR = 1008


class EventEmitter:
    def __init__(self, bus: EventBus) -> None:
        self._bus = bus

    def _emit(
        self,
        type_id: int,
        data: dict[str, Any],
    ) -> None:
        self._bus.emit(
            Event.create(
                type_id=type_id,
                data=data,
            )
        )

    def run_started(
        self,
        model: str,
        command_ir: dict,
        optimized_ir: dict,
    ) -> None:
        self._emit(
            AI_RUN_STARTED,
            {
                "model": model,
                "command_ir": command_ir,
                "optimized_ir": optimized_ir,
            },
        )

    def llm_prompt(
        self,
        system_prompt: str,
        messages: list,
        tool_def: list,
    ) -> None:
        self._emit(
            AI_LLM_PROMPT,
            {
                "system_prompt": system_prompt,
                "messages": messages,
                "tool_def": tool_def,
            },
        )

    def llm_response(
        self,
        response: Any,
        stop_reason: str,
        usage: dict,
    ) -> None:
        self._emit(
            AI_LLM_RESPONSE,
            {
                "response": response,
                "stop_reason": stop_reason,
                "usage": usage,
            },
        )

    def tool_call(
        self,
        tool: str,
        arguments: dict,
    ) -> None:
        self._emit(
            AI_TOOL_CALL,
            {
                "tool": tool,
                "arguments": arguments,
            },
        )

    def tool_result(
        self,
        tool: str,
        result: Any,
    ) -> None:
        self._emit(
            AI_TOOL_RESULT,
            {
                "tool": tool,
                "result": result,
            },
        )

    def user_input(
        self,
        input: str,
    ) -> None:
        self._emit(
            AI_USER_INPUT,
            {
                "input": input,
            },
        )

    def final_response(
        self,
        response: str,
    ) -> None:
        self._emit(
            AI_FINAL_RESPONSE,
            {
                "response": response,
            },
        )

    def error(
        self,
        error: str,
    ) -> None:
        self._emit(
            AI_ERROR,
            {
                "error": error,
            },
        )
